# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "mysql-connector-python" = super.buildPythonPackage rec {
    pname = "mysql-connector-python";
    version = "9.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/34/b6165e15fd45a8deb00932d8e7d823de7650270873b4044c4db6688e1d8f/mysql_connector_python-9.4.0-py2.py3-none-any.whl";
      sha256 = "1i02z0n1x2lasiy0yv4659ijqbg3kqmanvqpkcksnkbhkhb7krjn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "readkeys" = super.buildPythonPackage rec {
    pname = "readkeys";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/42/0be0768148dbc7d3f36d19e419edc3abd93ea05037b1debed50dfb880a4a/readkeys-1.0.2-py3-none-any.whl";
      sha256 = "1652yva8fbfrnrxk8k01dxbprdqp9hbiy0rbrrd4kpr60x7kq49b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sockets" = super.buildPythonPackage rec {
    pname = "sockets";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/84/bd124c5d3c012de593c45c7f0208615c73493859bbd5389e1403e311d387/sockets-1.0.0-py3-none-any.whl";
      sha256 = "02y9aws4dwb03cgmak0cy2qbxb0sqrrxsp65vkgdm2mp6w7qpdyd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
